Final Project
sneeu-leeu/space-travelers-hub pull request #37
Opened 2021-09-08 21:38 UTC by sneeu-leeu

## The Objectives of this projects:
- Use React documentation.
- Use React components.
- Use React props.
- Use React Router.
- Connect React and Redux.
- Handle events in a React app.
- Write unit tests with React Testing Library.
- Use styles in a React app.
- Use React life cycle methods.
- Apply, React best practices and language style guides in code.
- Use store, actions, and reducers in React.
- Perform a code review for a team member

2021-09-09 03:21 UTC, vichuge requested changes
# Required Changes ♻️ ⚠️ 🚦 

Hi dear student, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Good points 👍 
You used proper GitHub Flow ✔️
Your linter checks are all passing ✔️
Your PR messages are descriptive ✔️

## Aspects to improve ♻️

- [ ] I'm afraid I couldn't find your video presentation, I tried on your pull request description and readme file but I couldn't find it. Please, add the link for this (remember the video should follow all the requirements).

- [ ] It looks like your project doesn't have tests, please, I kindly invite you to add tests following the requirements.
![image](https://user-images.githubusercontent.com/20563252/132613624-ac996f0e-c1b4-425b-842a-1df7bf9272ef.png)


- [ ] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-09 03:21 UTC, vichuge commented on src/redux/missions/missions.js
> +};
- [ ] When you take the missions info at this point, you add every mission one by one user and action, a better way to do it is to add all of them in an object and once you're here on the reducer, add it with another switch option, that would save the memory cost to run an action a lot of times. Please use this on this redux. 🐶

2021-09-09 09:39 UTC, sneeu-leeu commented
Hi @vichuge, Thank you for taking the time to review our project! 

Could you please expand on your review regarding the tests? Our Project requirements only state to set up a testing environment. We have no required tests to write for this project on our documentation. What tests are you referring to?

2021-09-10 16:06 UTC, oxenprogrammer requested changes
Hi **@sneeu-leeu**  and **@uwadonat** , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet. :muscle:

**Changes Required**
Regarding the unit tests as pointed by the previous Code Reviewer, please refer to your learning objectives. To be precise, `bullet number 6`. You can find it [here](https://github.com/microverseinc/curriculum-react-redux/blob/main/group-project/project_space_travelers_hub.md).


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Consider the optional changes nice to have features and only work on them when you have satisfied the required changes_

Cheers and Happy coding!👏👏👏

2021-09-11 06:13 UTC, sneeu-leeu commented
@oxenprogrammer Thanks for the quick review. I am not going to ask for a second opinion purely for time reasons, but please read the entire document, not just the bullet points. There are NO TESTS required by Microverse for this project.

2021-09-11 07:59 UTC, MahmoudBakr23 commented
> @oxenprogrammer Thanks for the quick review. I am not going to ask for a second opinion purely for time reasons, but please read the entire document, not just the bullet points. There are NO TESTS required by Microverse for this project.

Hi team 😄 
Please note that as long as it is mentioned in the bullet points within the project requirements, then it's mandatory 🙏 Yet, tests are very important to work with, it helps you to understand the technologies you're working with more deeply and also, it makes you see your code from a different perspective 🙂

2021-09-11 07:59 UTC, MahmoudBakr23 requested changes
Hi team😃, 

Great job so far building this app and working on the requested changes. However, there's just a small thing left to do in order to get the approval 🙏 😄 

## Changes Required

_Please see the comment down below._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-11 07:59 UTC, MahmoudBakr23 commented on src/App.test.js
>  });
- [ ] Please add unit tests using the mentioned test libraries that you set up in your app 👍

2021-09-11 13:55 UTC, sneeu-leeu commented
@MahmoudBakr23  Thanks for your review. After reaching out to student success, we confirmed with Anne-Lore that this project does not need tests. Next reviewer, please read the entire document

2021-09-11 14:31 UTC, SpaYco commented
@sneeu-leeu please check:

https://github.com/microverseinc/curriculum-react-redux/blob/main/group-project/project_space_travelers_hub.md#learning-objectives

> Write unit tests with React Testing Library.

https://github.com/microverseinc/curriculum-react-redux/blob/main/group-project/project_space_travelers_hub.md#technical-set-up

> Set up testing libraries.

2021-09-11 15:10 UTC, Davidosky007 commented
## Hi @sneeu-leeu 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
* Kindly add unit tests to your project as it is a requirement [Check senior T.S.E response](https://github.com/sneeu-leeu/space-travelers-hub/pull/37#issuecomment-917417129l)
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-09-11 21:52 UTC, Emmyn5600 approved these changes
Hi Team,

Good job so far! 👏🏼 @sneeu-leeu  and @uwadonat

May I highlight the following:

- The repo looks professional.:heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:
- The project looks awesome:heavy_check_mark:
- Tests are passing successfully:heavy_check_mark: 
![cpp18](https://user-images.githubusercontent.com/55635977/132962513-b30b188d-1a87-45bc-b058-34f3c3f41a19.png)

## STATUS: APPROVED :muscle::clap:

Congratulations! :tada:
Your project is complete!  It's time to merge it :shipit:
Great work on implementing the changes requested by the previous reviewers.

#### Optional suggestions
 
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2021-09-12 09:32 UTC, merged